# 本机监听的IP和端口
local = ":13800"

# zookeeper地址
zkAddr = "localhost:2181"

# 所属的GROUP
groupId = "group1"

# 密码
secretKey = "123456"

# 这个客户端可以发送的Topic
pubs = [ "topic1", "topic2" ]

# 这个客户端可以消费的Topic
[[subs]]
# 消费的topic名字
topic = "topic1"
messageType = "msgType1"
bindType = 1
version = "v1"
watermark = 100
persistent = true

[[subs]]
topic = "topic2"
messageType = "msgType2"
bindType = 1
version = "v1"
watermark = 100
persistent = true